//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Intelbras.CRM2013.Domain.TabelaPrecoExtranet {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SellOutServiceBinding", Namespace="urn:extranet:intelbras.com.br")]
    public partial class SellOutServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LogarOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncluirPlanilhaTabelaPrecoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPlanilhasTabelaPrecoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SellOutServiceService() {
            this.Url = global::Intelbras.CRM2013.Domain.Properties.Settings.Default.Intelbras_CRM2013_Domain_TabelaPrecoExtranet_SellOutServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LogarCompletedEventHandler LogarCompleted;
        
        /// <remarks/>
        public event IncluirPlanilhaTabelaPrecoCompletedEventHandler IncluirPlanilhaTabelaPrecoCompleted;
        
        /// <remarks/>
        public event ListarPlanilhasTabelaPrecoCompletedEventHandler ListarPlanilhasTabelaPrecoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:extranet:intelbras.com.br#Logar", RequestNamespace="urn:extranet:intelbras.com.br", ResponseNamespace="urn:extranet:intelbras.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resposta Logar([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string email, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string senha, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool isHash) {
            object[] results = this.Invoke("Logar", new object[] {
                        email,
                        senha,
                        isHash});
            return ((Resposta)(results[0]));
        }
        
        /// <remarks/>
        public void LogarAsync(string email, string senha, bool isHash) {
            this.LogarAsync(email, senha, isHash, null);
        }
        
        /// <remarks/>
        public void LogarAsync(string email, string senha, bool isHash, object userState) {
            if ((this.LogarOperationCompleted == null)) {
                this.LogarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogarOperationCompleted);
            }
            this.InvokeAsync("Logar", new object[] {
                        email,
                        senha,
                        isHash}, this.LogarOperationCompleted, userState);
        }
        
        private void OnLogarOperationCompleted(object arg) {
            if ((this.LogarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogarCompleted(this, new LogarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:extranet:intelbras.com.br#IncluirPlanilhaTabelaPreco", RequestNamespace="urn:extranet:intelbras.com.br", ResponseNamespace="urn:extranet:intelbras.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resposta IncluirPlanilhaTabelaPreco([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string conta, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool gerarPSD, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool gerarPP, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool gerarPSCF, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool gerarValorNulo) {
            object[] results = this.Invoke("IncluirPlanilhaTabelaPreco", new object[] {
                        conta,
                        gerarPSD,
                        gerarPP,
                        gerarPSCF,
                        gerarValorNulo});
            return ((Resposta)(results[0]));
        }
        
        /// <remarks/>
        public void IncluirPlanilhaTabelaPrecoAsync(string conta, bool gerarPSD, bool gerarPP, bool gerarPSCF, bool gerarValorNulo) {
            this.IncluirPlanilhaTabelaPrecoAsync(conta, gerarPSD, gerarPP, gerarPSCF, gerarValorNulo, null);
        }
        
        /// <remarks/>
        public void IncluirPlanilhaTabelaPrecoAsync(string conta, bool gerarPSD, bool gerarPP, bool gerarPSCF, bool gerarValorNulo, object userState) {
            if ((this.IncluirPlanilhaTabelaPrecoOperationCompleted == null)) {
                this.IncluirPlanilhaTabelaPrecoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncluirPlanilhaTabelaPrecoOperationCompleted);
            }
            this.InvokeAsync("IncluirPlanilhaTabelaPreco", new object[] {
                        conta,
                        gerarPSD,
                        gerarPP,
                        gerarPSCF,
                        gerarValorNulo}, this.IncluirPlanilhaTabelaPrecoOperationCompleted, userState);
        }
        
        private void OnIncluirPlanilhaTabelaPrecoOperationCompleted(object arg) {
            if ((this.IncluirPlanilhaTabelaPrecoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncluirPlanilhaTabelaPrecoCompleted(this, new IncluirPlanilhaTabelaPrecoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:extranet:intelbras.com.br#ListarPlanilhasTabelaPreco", RequestNamespace="urn:extranet:intelbras.com.br", ResponseNamespace="urn:extranet:intelbras.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TabelaPrecoPlanilhaResposta ListarPlanilhasTabelaPreco([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string conta) {
            object[] results = this.Invoke("ListarPlanilhasTabelaPreco", new object[] {
                        conta});
            return ((TabelaPrecoPlanilhaResposta)(results[0]));
        }
        
        /// <remarks/>
        public void ListarPlanilhasTabelaPrecoAsync(string conta) {
            this.ListarPlanilhasTabelaPrecoAsync(conta, null);
        }
        
        /// <remarks/>
        public void ListarPlanilhasTabelaPrecoAsync(string conta, object userState) {
            if ((this.ListarPlanilhasTabelaPrecoOperationCompleted == null)) {
                this.ListarPlanilhasTabelaPrecoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPlanilhasTabelaPrecoOperationCompleted);
            }
            this.InvokeAsync("ListarPlanilhasTabelaPreco", new object[] {
                        conta}, this.ListarPlanilhasTabelaPrecoOperationCompleted, userState);
        }
        
        private void OnListarPlanilhasTabelaPrecoOperationCompleted(object arg) {
            if ((this.ListarPlanilhasTabelaPrecoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPlanilhasTabelaPrecoCompleted(this, new ListarPlanilhasTabelaPrecoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:extranet:intelbras.com.br")]
    public partial class Resposta {
        
        private System.Nullable<bool> resultadoField;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool> resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/soap/encoding/")]
    public partial class Array {
        
        private System.Xml.XmlElement[] anyField;
        
        private string arrayTypeField;
        
        private string offsetField;
        
        private bool offsetFieldSpecified;
        
        private string idField;
        
        private string hrefField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string arrayType {
            get {
                return this.arrayTypeField;
            }
            set {
                this.arrayTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:extranet:intelbras.com.br")]
    public partial class TabelaPrecoPlanilhaResposta {
        
        private System.Nullable<bool> resultadoField;
        
        private string mensagemField;
        
        private Array planilhasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool> resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Array planilhas {
            get {
                return this.planilhasField;
            }
            set {
                this.planilhasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void LogarCompletedEventHandler(object sender, LogarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resposta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resposta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void IncluirPlanilhaTabelaPrecoCompletedEventHandler(object sender, IncluirPlanilhaTabelaPrecoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncluirPlanilhaTabelaPrecoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncluirPlanilhaTabelaPrecoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resposta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resposta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListarPlanilhasTabelaPrecoCompletedEventHandler(object sender, ListarPlanilhasTabelaPrecoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPlanilhasTabelaPrecoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPlanilhasTabelaPrecoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TabelaPrecoPlanilhaResposta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TabelaPrecoPlanilhaResposta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591