//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelbras.CRM2013.Tests.WsCrm4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices", ConfigurationName="WsCrm4.ConsultaCRM4Soap")]
    public interface ConsultaCRM4Soap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento CNPJ no namespace http://schemas.microsoft.com/crm/2009/WebServices não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/crm/2009/WebServices/ContaCRM4", ReplyAction="*")]
        Intelbras.CRM2013.Tests.WsCrm4.ContaCRM4Response ContaCRM4(Intelbras.CRM2013.Tests.WsCrm4.ContaCRM4Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContaCRM4Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ContaCRM4", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public Intelbras.CRM2013.Tests.WsCrm4.ContaCRM4RequestBody Body;
        
        public ContaCRM4Request() {
        }
        
        public ContaCRM4Request(Intelbras.CRM2013.Tests.WsCrm4.ContaCRM4RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class ContaCRM4RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CNPJ;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodigoEmitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GuidCRM2013;
        
        public ContaCRM4RequestBody() {
        }
        
        public ContaCRM4RequestBody(string CNPJ, string CodigoEmitente, string GuidCRM2013) {
            this.CNPJ = CNPJ;
            this.CodigoEmitente = CodigoEmitente;
            this.GuidCRM2013 = GuidCRM2013;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContaCRM4Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ContaCRM4Response", Namespace="http://schemas.microsoft.com/crm/2009/WebServices", Order=0)]
        public Intelbras.CRM2013.Tests.WsCrm4.ContaCRM4ResponseBody Body;
        
        public ContaCRM4Response() {
        }
        
        public ContaCRM4Response(Intelbras.CRM2013.Tests.WsCrm4.ContaCRM4ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2009/WebServices")]
    public partial class ContaCRM4ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ContaCRM4Result;
        
        public ContaCRM4ResponseBody() {
        }
        
        public ContaCRM4ResponseBody(System.Xml.Linq.XElement ContaCRM4Result) {
            this.ContaCRM4Result = ContaCRM4Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaCRM4SoapChannel : Intelbras.CRM2013.Tests.WsCrm4.ConsultaCRM4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaCRM4SoapClient : System.ServiceModel.ClientBase<Intelbras.CRM2013.Tests.WsCrm4.ConsultaCRM4Soap>, Intelbras.CRM2013.Tests.WsCrm4.ConsultaCRM4Soap {
        
        public ConsultaCRM4SoapClient() {
        }
        
        public ConsultaCRM4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaCRM4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaCRM4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaCRM4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Intelbras.CRM2013.Tests.WsCrm4.ContaCRM4Response Intelbras.CRM2013.Tests.WsCrm4.ConsultaCRM4Soap.ContaCRM4(Intelbras.CRM2013.Tests.WsCrm4.ContaCRM4Request request) {
            return base.Channel.ContaCRM4(request);
        }
        
        public System.Xml.Linq.XElement ContaCRM4(string CNPJ, string CodigoEmitente, string GuidCRM2013) {
            Intelbras.CRM2013.Tests.WsCrm4.ContaCRM4Request inValue = new Intelbras.CRM2013.Tests.WsCrm4.ContaCRM4Request();
            inValue.Body = new Intelbras.CRM2013.Tests.WsCrm4.ContaCRM4RequestBody();
            inValue.Body.CNPJ = CNPJ;
            inValue.Body.CodigoEmitente = CodigoEmitente;
            inValue.Body.GuidCRM2013 = GuidCRM2013;
            Intelbras.CRM2013.Tests.WsCrm4.ContaCRM4Response retVal = ((Intelbras.CRM2013.Tests.WsCrm4.ConsultaCRM4Soap)(this)).ContaCRM4(inValue);
            return retVal.Body.ContaCRM4Result;
        }
    }
}
