//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Intelbras.CRM2013.Domain.Sellout {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SellOutCRMWSSoap", Namespace="http://tempuri.org/")]
    public partial class SellOutCRMWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PersistirProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MudarStatusProdutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MudarStatusRevendaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MudarStatusDistribuidorOperationCompleted;
        
        private System.Threading.SendOrPostCallback PersistirRevendaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarContagemVendaOperationCompleted;
        
        private System.Threading.SendOrPostCallback PersistirDistribuidorOperationCompleted;
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SellOutCRMWS() {
            this.Url = global::Intelbras.CRM2013.Domain.Properties.Settings.Default.Intelbras_CRM2013_Domain_Sellout_SellOutCRMWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PersistirProdutoCompletedEventHandler PersistirProdutoCompleted;
        
        /// <remarks/>
        public event MudarStatusProdutoCompletedEventHandler MudarStatusProdutoCompleted;
        
        /// <remarks/>
        public event MudarStatusRevendaCompletedEventHandler MudarStatusRevendaCompleted;
        
        /// <remarks/>
        public event MudarStatusDistribuidorCompletedEventHandler MudarStatusDistribuidorCompleted;
        
        /// <remarks/>
        public event PersistirRevendaCompletedEventHandler PersistirRevendaCompleted;
        
        /// <remarks/>
        public event listarContagemVendaCompletedEventHandler listarContagemVendaCompleted;
        
        /// <remarks/>
        public event PersistirDistribuidorCompletedEventHandler PersistirDistribuidorCompleted;
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PersistirProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PersistirProduto(string usuario, string senha, string xml, out string resposta) {
            object[] results = this.Invoke("PersistirProduto", new object[] {
                        usuario,
                        senha,
                        xml});
            resposta = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PersistirProdutoAsync(string usuario, string senha, string xml) {
            this.PersistirProdutoAsync(usuario, senha, xml, null);
        }
        
        /// <remarks/>
        public void PersistirProdutoAsync(string usuario, string senha, string xml, object userState) {
            if ((this.PersistirProdutoOperationCompleted == null)) {
                this.PersistirProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPersistirProdutoOperationCompleted);
            }
            this.InvokeAsync("PersistirProduto", new object[] {
                        usuario,
                        senha,
                        xml}, this.PersistirProdutoOperationCompleted, userState);
        }
        
        private void OnPersistirProdutoOperationCompleted(object arg) {
            if ((this.PersistirProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PersistirProdutoCompleted(this, new PersistirProdutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MudarStatusProduto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MudarStatusProduto(string usuario, string senha, string xml, out string resposta) {
            object[] results = this.Invoke("MudarStatusProduto", new object[] {
                        usuario,
                        senha,
                        xml});
            resposta = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MudarStatusProdutoAsync(string usuario, string senha, string xml) {
            this.MudarStatusProdutoAsync(usuario, senha, xml, null);
        }
        
        /// <remarks/>
        public void MudarStatusProdutoAsync(string usuario, string senha, string xml, object userState) {
            if ((this.MudarStatusProdutoOperationCompleted == null)) {
                this.MudarStatusProdutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMudarStatusProdutoOperationCompleted);
            }
            this.InvokeAsync("MudarStatusProduto", new object[] {
                        usuario,
                        senha,
                        xml}, this.MudarStatusProdutoOperationCompleted, userState);
        }
        
        private void OnMudarStatusProdutoOperationCompleted(object arg) {
            if ((this.MudarStatusProdutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MudarStatusProdutoCompleted(this, new MudarStatusProdutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MudarStatusRevenda", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MudarStatusRevenda(string usuario, string senha, string xml, out string resposta) {
            object[] results = this.Invoke("MudarStatusRevenda", new object[] {
                        usuario,
                        senha,
                        xml});
            resposta = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MudarStatusRevendaAsync(string usuario, string senha, string xml) {
            this.MudarStatusRevendaAsync(usuario, senha, xml, null);
        }
        
        /// <remarks/>
        public void MudarStatusRevendaAsync(string usuario, string senha, string xml, object userState) {
            if ((this.MudarStatusRevendaOperationCompleted == null)) {
                this.MudarStatusRevendaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMudarStatusRevendaOperationCompleted);
            }
            this.InvokeAsync("MudarStatusRevenda", new object[] {
                        usuario,
                        senha,
                        xml}, this.MudarStatusRevendaOperationCompleted, userState);
        }
        
        private void OnMudarStatusRevendaOperationCompleted(object arg) {
            if ((this.MudarStatusRevendaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MudarStatusRevendaCompleted(this, new MudarStatusRevendaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MudarStatusDistribuidor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MudarStatusDistribuidor(string usuario, string senha, string xml, out string resposta) {
            object[] results = this.Invoke("MudarStatusDistribuidor", new object[] {
                        usuario,
                        senha,
                        xml});
            resposta = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MudarStatusDistribuidorAsync(string usuario, string senha, string xml) {
            this.MudarStatusDistribuidorAsync(usuario, senha, xml, null);
        }
        
        /// <remarks/>
        public void MudarStatusDistribuidorAsync(string usuario, string senha, string xml, object userState) {
            if ((this.MudarStatusDistribuidorOperationCompleted == null)) {
                this.MudarStatusDistribuidorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMudarStatusDistribuidorOperationCompleted);
            }
            this.InvokeAsync("MudarStatusDistribuidor", new object[] {
                        usuario,
                        senha,
                        xml}, this.MudarStatusDistribuidorOperationCompleted, userState);
        }
        
        private void OnMudarStatusDistribuidorOperationCompleted(object arg) {
            if ((this.MudarStatusDistribuidorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MudarStatusDistribuidorCompleted(this, new MudarStatusDistribuidorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PersistirRevenda", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PersistirRevenda(string usuario, string senha, string xml, out string resposta) {
            object[] results = this.Invoke("PersistirRevenda", new object[] {
                        usuario,
                        senha,
                        xml});
            resposta = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PersistirRevendaAsync(string usuario, string senha, string xml) {
            this.PersistirRevendaAsync(usuario, senha, xml, null);
        }
        
        /// <remarks/>
        public void PersistirRevendaAsync(string usuario, string senha, string xml, object userState) {
            if ((this.PersistirRevendaOperationCompleted == null)) {
                this.PersistirRevendaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPersistirRevendaOperationCompleted);
            }
            this.InvokeAsync("PersistirRevenda", new object[] {
                        usuario,
                        senha,
                        xml}, this.PersistirRevendaOperationCompleted, userState);
        }
        
        private void OnPersistirRevendaOperationCompleted(object arg) {
            if ((this.PersistirRevendaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PersistirRevendaCompleted(this, new PersistirRevendaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarContagemVenda", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public QtdProdutoSellout[] listarContagemVenda(System.DateTime dataIni, System.DateTime dataFim, System.Guid distGuid, string listaProdIds) {
            object[] results = this.Invoke("listarContagemVenda", new object[] {
                        dataIni,
                        dataFim,
                        distGuid,
                        listaProdIds});
            return ((QtdProdutoSellout[])(results[0]));
        }
        
        /// <remarks/>
        public void listarContagemVendaAsync(System.DateTime dataIni, System.DateTime dataFim, System.Guid distGuid, string listaProdIds) {
            this.listarContagemVendaAsync(dataIni, dataFim, distGuid, listaProdIds, null);
        }
        
        /// <remarks/>
        public void listarContagemVendaAsync(System.DateTime dataIni, System.DateTime dataFim, System.Guid distGuid, string listaProdIds, object userState) {
            if ((this.listarContagemVendaOperationCompleted == null)) {
                this.listarContagemVendaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarContagemVendaOperationCompleted);
            }
            this.InvokeAsync("listarContagemVenda", new object[] {
                        dataIni,
                        dataFim,
                        distGuid,
                        listaProdIds}, this.listarContagemVendaOperationCompleted, userState);
        }
        
        private void OnlistarContagemVendaOperationCompleted(object arg) {
            if ((this.listarContagemVendaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarContagemVendaCompleted(this, new listarContagemVendaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PersistirDistribuidor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PersistirDistribuidor(string usuario, string senha, string xml, out string resposta) {
            object[] results = this.Invoke("PersistirDistribuidor", new object[] {
                        usuario,
                        senha,
                        xml});
            resposta = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PersistirDistribuidorAsync(string usuario, string senha, string xml) {
            this.PersistirDistribuidorAsync(usuario, senha, xml, null);
        }
        
        /// <remarks/>
        public void PersistirDistribuidorAsync(string usuario, string senha, string xml, object userState) {
            if ((this.PersistirDistribuidorOperationCompleted == null)) {
                this.PersistirDistribuidorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPersistirDistribuidorOperationCompleted);
            }
            this.InvokeAsync("PersistirDistribuidor", new object[] {
                        usuario,
                        senha,
                        xml}, this.PersistirDistribuidorOperationCompleted, userState);
        }
        
        private void OnPersistirDistribuidorOperationCompleted(object arg) {
            if ((this.PersistirDistribuidorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PersistirDistribuidorCompleted(this, new PersistirDistribuidorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ping", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Ping() {
            object[] results = this.Invoke("Ping", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QtdProdutoSellout {
        
        private string codigoProdutoERPField;
        
        private decimal totalUnidadesField;
        
        /// <remarks/>
        public string CodigoProdutoERP {
            get {
                return this.codigoProdutoERPField;
            }
            set {
                this.codigoProdutoERPField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalUnidades {
            get {
                return this.totalUnidadesField;
            }
            set {
                this.totalUnidadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void PersistirProdutoCompletedEventHandler(object sender, PersistirProdutoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersistirProdutoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PersistirProdutoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string resposta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void MudarStatusProdutoCompletedEventHandler(object sender, MudarStatusProdutoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MudarStatusProdutoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MudarStatusProdutoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string resposta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void MudarStatusRevendaCompletedEventHandler(object sender, MudarStatusRevendaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MudarStatusRevendaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MudarStatusRevendaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string resposta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void MudarStatusDistribuidorCompletedEventHandler(object sender, MudarStatusDistribuidorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MudarStatusDistribuidorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MudarStatusDistribuidorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string resposta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void PersistirRevendaCompletedEventHandler(object sender, PersistirRevendaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersistirRevendaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PersistirRevendaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string resposta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void listarContagemVendaCompletedEventHandler(object sender, listarContagemVendaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarContagemVendaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarContagemVendaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QtdProdutoSellout[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QtdProdutoSellout[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void PersistirDistribuidorCompletedEventHandler(object sender, PersistirDistribuidorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersistirDistribuidorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PersistirDistribuidorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string resposta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591