//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelbras.CRM2013.Tests.SellOutWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SellOutWebService.SelloutWSSoap")]
    public interface SelloutWSSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarPlanilhaSellOut", ReplyAction="*")]
        Intelbras.CRM2013.Tests.SellOutWebService.EnviarPlanilhaSellOutResponse EnviarPlanilhaSellOut(Intelbras.CRM2013.Tests.SellOutWebService.EnviarPlanilhaSellOutRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarStatusPlanilha", ReplyAction="*")]
        Intelbras.CRM2013.Tests.SellOutWebService.VerificarStatusPlanilhaResponse VerificarStatusPlanilha(Intelbras.CRM2013.Tests.SellOutWebService.VerificarStatusPlanilhaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnvioSellout", ReplyAction="*")]
        Intelbras.CRM2013.Tests.SellOutWebService.EnvioSelloutResponse EnvioSellout(Intelbras.CRM2013.Tests.SellOutWebService.EnvioSelloutRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersistirProduto", ReplyAction="*")]
        Intelbras.CRM2013.Tests.SellOutWebService.PersistirProdutoResponse PersistirProduto(Intelbras.CRM2013.Tests.SellOutWebService.PersistirProdutoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MudarStatusProduto", ReplyAction="*")]
        Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusProdutoResponse MudarStatusProduto(Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusProdutoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MudarStatusRevenda", ReplyAction="*")]
        Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusRevendaResponse MudarStatusRevenda(Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusRevendaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MudarStatusDistribuidor", ReplyAction="*")]
        Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusDistribuidorResponse MudarStatusDistribuidor(Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusDistribuidorRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersistirRevenda", ReplyAction="*")]
        Intelbras.CRM2013.Tests.SellOutWebService.PersistirRevendaResponse PersistirRevenda(Intelbras.CRM2013.Tests.SellOutWebService.PersistirRevendaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersistirDistribuidor", ReplyAction="*")]
        Intelbras.CRM2013.Tests.SellOutWebService.PersistirDistribuidorResponse PersistirDistribuidor(Intelbras.CRM2013.Tests.SellOutWebService.PersistirDistribuidorRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirDeParaProdutoCanal", ReplyAction="*")]
        Intelbras.CRM2013.Tests.SellOutWebService.InserirDeParaProdutoCanalResponse InserirDeParaProdutoCanal(Intelbras.CRM2013.Tests.SellOutWebService.InserirDeParaProdutoCanalRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuario no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirSaldoEstoque", ReplyAction="*")]
        Intelbras.CRM2013.Tests.SellOutWebService.InserirSaldoEstoqueResponse InserirSaldoEstoque(Intelbras.CRM2013.Tests.SellOutWebService.InserirSaldoEstoqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping", ReplyAction="*")]
        bool Ping();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarPlanilhaSellOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarPlanilhaSellOut", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.EnviarPlanilhaSellOutRequestBody Body;
        
        public EnviarPlanilhaSellOutRequest() {
        }
        
        public EnviarPlanilhaSellOutRequest(Intelbras.CRM2013.Tests.SellOutWebService.EnviarPlanilhaSellOutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarPlanilhaSellOutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml;
        
        public EnviarPlanilhaSellOutRequestBody() {
        }
        
        public EnviarPlanilhaSellOutRequestBody(string usuario, string senha, string xml) {
            this.usuario = usuario;
            this.senha = senha;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarPlanilhaSellOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarPlanilhaSellOutResponse", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.EnviarPlanilhaSellOutResponseBody Body;
        
        public EnviarPlanilhaSellOutResponse() {
        }
        
        public EnviarPlanilhaSellOutResponse(Intelbras.CRM2013.Tests.SellOutWebService.EnviarPlanilhaSellOutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarPlanilhaSellOutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EnviarPlanilhaSellOutResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resposta;
        
        public EnviarPlanilhaSellOutResponseBody() {
        }
        
        public EnviarPlanilhaSellOutResponseBody(bool EnviarPlanilhaSellOutResult, string resposta) {
            this.EnviarPlanilhaSellOutResult = EnviarPlanilhaSellOutResult;
            this.resposta = resposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarStatusPlanilhaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarStatusPlanilha", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.VerificarStatusPlanilhaRequestBody Body;
        
        public VerificarStatusPlanilhaRequest() {
        }
        
        public VerificarStatusPlanilhaRequest(Intelbras.CRM2013.Tests.SellOutWebService.VerificarStatusPlanilhaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarStatusPlanilhaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml;
        
        public VerificarStatusPlanilhaRequestBody() {
        }
        
        public VerificarStatusPlanilhaRequestBody(string usuario, string senha, string xml) {
            this.usuario = usuario;
            this.senha = senha;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarStatusPlanilhaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarStatusPlanilhaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.VerificarStatusPlanilhaResponseBody Body;
        
        public VerificarStatusPlanilhaResponse() {
        }
        
        public VerificarStatusPlanilhaResponse(Intelbras.CRM2013.Tests.SellOutWebService.VerificarStatusPlanilhaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarStatusPlanilhaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerificarStatusPlanilhaResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resposta;
        
        public VerificarStatusPlanilhaResponseBody() {
        }
        
        public VerificarStatusPlanilhaResponseBody(string VerificarStatusPlanilhaResult, string resposta) {
            this.VerificarStatusPlanilhaResult = VerificarStatusPlanilhaResult;
            this.resposta = resposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioSelloutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioSellout", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.EnvioSelloutRequestBody Body;
        
        public EnvioSelloutRequest() {
        }
        
        public EnvioSelloutRequest(Intelbras.CRM2013.Tests.SellOutWebService.EnvioSelloutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnvioSelloutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml;
        
        public EnvioSelloutRequestBody() {
        }
        
        public EnvioSelloutRequestBody(string usuario, string senha, string xml) {
            this.usuario = usuario;
            this.senha = senha;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioSelloutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioSelloutResponse", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.EnvioSelloutResponseBody Body;
        
        public EnvioSelloutResponse() {
        }
        
        public EnvioSelloutResponse(Intelbras.CRM2013.Tests.SellOutWebService.EnvioSelloutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnvioSelloutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EnvioSelloutResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resposta;
        
        public EnvioSelloutResponseBody() {
        }
        
        public EnvioSelloutResponseBody(bool EnvioSelloutResult, string resposta) {
            this.EnvioSelloutResult = EnvioSelloutResult;
            this.resposta = resposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersistirProdutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersistirProduto", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.PersistirProdutoRequestBody Body;
        
        public PersistirProdutoRequest() {
        }
        
        public PersistirProdutoRequest(Intelbras.CRM2013.Tests.SellOutWebService.PersistirProdutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PersistirProdutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml;
        
        public PersistirProdutoRequestBody() {
        }
        
        public PersistirProdutoRequestBody(string usuario, string senha, string xml) {
            this.usuario = usuario;
            this.senha = senha;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersistirProdutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersistirProdutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.PersistirProdutoResponseBody Body;
        
        public PersistirProdutoResponse() {
        }
        
        public PersistirProdutoResponse(Intelbras.CRM2013.Tests.SellOutWebService.PersistirProdutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PersistirProdutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PersistirProdutoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resposta;
        
        public PersistirProdutoResponseBody() {
        }
        
        public PersistirProdutoResponseBody(bool PersistirProdutoResult, string resposta) {
            this.PersistirProdutoResult = PersistirProdutoResult;
            this.resposta = resposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MudarStatusProdutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MudarStatusProduto", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusProdutoRequestBody Body;
        
        public MudarStatusProdutoRequest() {
        }
        
        public MudarStatusProdutoRequest(Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusProdutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MudarStatusProdutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml;
        
        public MudarStatusProdutoRequestBody() {
        }
        
        public MudarStatusProdutoRequestBody(string usuario, string senha, string xml) {
            this.usuario = usuario;
            this.senha = senha;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MudarStatusProdutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MudarStatusProdutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusProdutoResponseBody Body;
        
        public MudarStatusProdutoResponse() {
        }
        
        public MudarStatusProdutoResponse(Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusProdutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MudarStatusProdutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MudarStatusProdutoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resposta;
        
        public MudarStatusProdutoResponseBody() {
        }
        
        public MudarStatusProdutoResponseBody(bool MudarStatusProdutoResult, string resposta) {
            this.MudarStatusProdutoResult = MudarStatusProdutoResult;
            this.resposta = resposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MudarStatusRevendaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MudarStatusRevenda", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusRevendaRequestBody Body;
        
        public MudarStatusRevendaRequest() {
        }
        
        public MudarStatusRevendaRequest(Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusRevendaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MudarStatusRevendaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml;
        
        public MudarStatusRevendaRequestBody() {
        }
        
        public MudarStatusRevendaRequestBody(string usuario, string senha, string xml) {
            this.usuario = usuario;
            this.senha = senha;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MudarStatusRevendaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MudarStatusRevendaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusRevendaResponseBody Body;
        
        public MudarStatusRevendaResponse() {
        }
        
        public MudarStatusRevendaResponse(Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusRevendaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MudarStatusRevendaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MudarStatusRevendaResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resposta;
        
        public MudarStatusRevendaResponseBody() {
        }
        
        public MudarStatusRevendaResponseBody(bool MudarStatusRevendaResult, string resposta) {
            this.MudarStatusRevendaResult = MudarStatusRevendaResult;
            this.resposta = resposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MudarStatusDistribuidorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MudarStatusDistribuidor", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusDistribuidorRequestBody Body;
        
        public MudarStatusDistribuidorRequest() {
        }
        
        public MudarStatusDistribuidorRequest(Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusDistribuidorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MudarStatusDistribuidorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml;
        
        public MudarStatusDistribuidorRequestBody() {
        }
        
        public MudarStatusDistribuidorRequestBody(string usuario, string senha, string xml) {
            this.usuario = usuario;
            this.senha = senha;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MudarStatusDistribuidorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MudarStatusDistribuidorResponse", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusDistribuidorResponseBody Body;
        
        public MudarStatusDistribuidorResponse() {
        }
        
        public MudarStatusDistribuidorResponse(Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusDistribuidorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MudarStatusDistribuidorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MudarStatusDistribuidorResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resposta;
        
        public MudarStatusDistribuidorResponseBody() {
        }
        
        public MudarStatusDistribuidorResponseBody(bool MudarStatusDistribuidorResult, string resposta) {
            this.MudarStatusDistribuidorResult = MudarStatusDistribuidorResult;
            this.resposta = resposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersistirRevendaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersistirRevenda", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.PersistirRevendaRequestBody Body;
        
        public PersistirRevendaRequest() {
        }
        
        public PersistirRevendaRequest(Intelbras.CRM2013.Tests.SellOutWebService.PersistirRevendaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PersistirRevendaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml;
        
        public PersistirRevendaRequestBody() {
        }
        
        public PersistirRevendaRequestBody(string usuario, string senha, string xml) {
            this.usuario = usuario;
            this.senha = senha;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersistirRevendaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersistirRevendaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.PersistirRevendaResponseBody Body;
        
        public PersistirRevendaResponse() {
        }
        
        public PersistirRevendaResponse(Intelbras.CRM2013.Tests.SellOutWebService.PersistirRevendaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PersistirRevendaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PersistirRevendaResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resposta;
        
        public PersistirRevendaResponseBody() {
        }
        
        public PersistirRevendaResponseBody(bool PersistirRevendaResult, string resposta) {
            this.PersistirRevendaResult = PersistirRevendaResult;
            this.resposta = resposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersistirDistribuidorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersistirDistribuidor", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.PersistirDistribuidorRequestBody Body;
        
        public PersistirDistribuidorRequest() {
        }
        
        public PersistirDistribuidorRequest(Intelbras.CRM2013.Tests.SellOutWebService.PersistirDistribuidorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PersistirDistribuidorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml;
        
        public PersistirDistribuidorRequestBody() {
        }
        
        public PersistirDistribuidorRequestBody(string usuario, string senha, string xml) {
            this.usuario = usuario;
            this.senha = senha;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersistirDistribuidorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersistirDistribuidorResponse", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.PersistirDistribuidorResponseBody Body;
        
        public PersistirDistribuidorResponse() {
        }
        
        public PersistirDistribuidorResponse(Intelbras.CRM2013.Tests.SellOutWebService.PersistirDistribuidorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PersistirDistribuidorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PersistirDistribuidorResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resposta;
        
        public PersistirDistribuidorResponseBody() {
        }
        
        public PersistirDistribuidorResponseBody(bool PersistirDistribuidorResult, string resposta) {
            this.PersistirDistribuidorResult = PersistirDistribuidorResult;
            this.resposta = resposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirDeParaProdutoCanalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirDeParaProdutoCanal", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.InserirDeParaProdutoCanalRequestBody Body;
        
        public InserirDeParaProdutoCanalRequest() {
        }
        
        public InserirDeParaProdutoCanalRequest(Intelbras.CRM2013.Tests.SellOutWebService.InserirDeParaProdutoCanalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirDeParaProdutoCanalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml;
        
        public InserirDeParaProdutoCanalRequestBody() {
        }
        
        public InserirDeParaProdutoCanalRequestBody(string usuario, string senha, string xml) {
            this.usuario = usuario;
            this.senha = senha;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirDeParaProdutoCanalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirDeParaProdutoCanalResponse", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.InserirDeParaProdutoCanalResponseBody Body;
        
        public InserirDeParaProdutoCanalResponse() {
        }
        
        public InserirDeParaProdutoCanalResponse(Intelbras.CRM2013.Tests.SellOutWebService.InserirDeParaProdutoCanalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirDeParaProdutoCanalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InserirDeParaProdutoCanalResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resposta;
        
        public InserirDeParaProdutoCanalResponseBody() {
        }
        
        public InserirDeParaProdutoCanalResponseBody(bool InserirDeParaProdutoCanalResult, string resposta) {
            this.InserirDeParaProdutoCanalResult = InserirDeParaProdutoCanalResult;
            this.resposta = resposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirSaldoEstoqueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirSaldoEstoque", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.InserirSaldoEstoqueRequestBody Body;
        
        public InserirSaldoEstoqueRequest() {
        }
        
        public InserirSaldoEstoqueRequest(Intelbras.CRM2013.Tests.SellOutWebService.InserirSaldoEstoqueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirSaldoEstoqueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xml;
        
        public InserirSaldoEstoqueRequestBody() {
        }
        
        public InserirSaldoEstoqueRequestBody(string usuario, string senha, string xml) {
            this.usuario = usuario;
            this.senha = senha;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirSaldoEstoqueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirSaldoEstoqueResponse", Namespace="http://tempuri.org/", Order=0)]
        public Intelbras.CRM2013.Tests.SellOutWebService.InserirSaldoEstoqueResponseBody Body;
        
        public InserirSaldoEstoqueResponse() {
        }
        
        public InserirSaldoEstoqueResponse(Intelbras.CRM2013.Tests.SellOutWebService.InserirSaldoEstoqueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirSaldoEstoqueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InserirSaldoEstoqueResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resposta;
        
        public InserirSaldoEstoqueResponseBody() {
        }
        
        public InserirSaldoEstoqueResponseBody(bool InserirSaldoEstoqueResult, string resposta) {
            this.InserirSaldoEstoqueResult = InserirSaldoEstoqueResult;
            this.resposta = resposta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SelloutWSSoapChannel : Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelloutWSSoapClient : System.ServiceModel.ClientBase<Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap>, Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap {
        
        public SelloutWSSoapClient() {
        }
        
        public SelloutWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SelloutWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelloutWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelloutWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Intelbras.CRM2013.Tests.SellOutWebService.EnviarPlanilhaSellOutResponse Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap.EnviarPlanilhaSellOut(Intelbras.CRM2013.Tests.SellOutWebService.EnviarPlanilhaSellOutRequest request) {
            return base.Channel.EnviarPlanilhaSellOut(request);
        }
        
        public bool EnviarPlanilhaSellOut(string usuario, string senha, string xml, out string resposta) {
            Intelbras.CRM2013.Tests.SellOutWebService.EnviarPlanilhaSellOutRequest inValue = new Intelbras.CRM2013.Tests.SellOutWebService.EnviarPlanilhaSellOutRequest();
            inValue.Body = new Intelbras.CRM2013.Tests.SellOutWebService.EnviarPlanilhaSellOutRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.senha = senha;
            inValue.Body.xml = xml;
            Intelbras.CRM2013.Tests.SellOutWebService.EnviarPlanilhaSellOutResponse retVal = ((Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap)(this)).EnviarPlanilhaSellOut(inValue);
            resposta = retVal.Body.resposta;
            return retVal.Body.EnviarPlanilhaSellOutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Intelbras.CRM2013.Tests.SellOutWebService.VerificarStatusPlanilhaResponse Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap.VerificarStatusPlanilha(Intelbras.CRM2013.Tests.SellOutWebService.VerificarStatusPlanilhaRequest request) {
            return base.Channel.VerificarStatusPlanilha(request);
        }
        
        public string VerificarStatusPlanilha(string usuario, string senha, string xml, out string resposta) {
            Intelbras.CRM2013.Tests.SellOutWebService.VerificarStatusPlanilhaRequest inValue = new Intelbras.CRM2013.Tests.SellOutWebService.VerificarStatusPlanilhaRequest();
            inValue.Body = new Intelbras.CRM2013.Tests.SellOutWebService.VerificarStatusPlanilhaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.senha = senha;
            inValue.Body.xml = xml;
            Intelbras.CRM2013.Tests.SellOutWebService.VerificarStatusPlanilhaResponse retVal = ((Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap)(this)).VerificarStatusPlanilha(inValue);
            resposta = retVal.Body.resposta;
            return retVal.Body.VerificarStatusPlanilhaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Intelbras.CRM2013.Tests.SellOutWebService.EnvioSelloutResponse Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap.EnvioSellout(Intelbras.CRM2013.Tests.SellOutWebService.EnvioSelloutRequest request) {
            return base.Channel.EnvioSellout(request);
        }
        
        public bool EnvioSellout(string usuario, string senha, string xml, out string resposta) {
            Intelbras.CRM2013.Tests.SellOutWebService.EnvioSelloutRequest inValue = new Intelbras.CRM2013.Tests.SellOutWebService.EnvioSelloutRequest();
            inValue.Body = new Intelbras.CRM2013.Tests.SellOutWebService.EnvioSelloutRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.senha = senha;
            inValue.Body.xml = xml;
            Intelbras.CRM2013.Tests.SellOutWebService.EnvioSelloutResponse retVal = ((Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap)(this)).EnvioSellout(inValue);
            resposta = retVal.Body.resposta;
            return retVal.Body.EnvioSelloutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Intelbras.CRM2013.Tests.SellOutWebService.PersistirProdutoResponse Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap.PersistirProduto(Intelbras.CRM2013.Tests.SellOutWebService.PersistirProdutoRequest request) {
            return base.Channel.PersistirProduto(request);
        }
        
        public bool PersistirProduto(string usuario, string senha, string xml, out string resposta) {
            Intelbras.CRM2013.Tests.SellOutWebService.PersistirProdutoRequest inValue = new Intelbras.CRM2013.Tests.SellOutWebService.PersistirProdutoRequest();
            inValue.Body = new Intelbras.CRM2013.Tests.SellOutWebService.PersistirProdutoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.senha = senha;
            inValue.Body.xml = xml;
            Intelbras.CRM2013.Tests.SellOutWebService.PersistirProdutoResponse retVal = ((Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap)(this)).PersistirProduto(inValue);
            resposta = retVal.Body.resposta;
            return retVal.Body.PersistirProdutoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusProdutoResponse Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap.MudarStatusProduto(Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusProdutoRequest request) {
            return base.Channel.MudarStatusProduto(request);
        }
        
        public bool MudarStatusProduto(string usuario, string senha, string xml, out string resposta) {
            Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusProdutoRequest inValue = new Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusProdutoRequest();
            inValue.Body = new Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusProdutoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.senha = senha;
            inValue.Body.xml = xml;
            Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusProdutoResponse retVal = ((Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap)(this)).MudarStatusProduto(inValue);
            resposta = retVal.Body.resposta;
            return retVal.Body.MudarStatusProdutoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusRevendaResponse Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap.MudarStatusRevenda(Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusRevendaRequest request) {
            return base.Channel.MudarStatusRevenda(request);
        }
        
        public bool MudarStatusRevenda(string usuario, string senha, string xml, out string resposta) {
            Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusRevendaRequest inValue = new Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusRevendaRequest();
            inValue.Body = new Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusRevendaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.senha = senha;
            inValue.Body.xml = xml;
            Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusRevendaResponse retVal = ((Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap)(this)).MudarStatusRevenda(inValue);
            resposta = retVal.Body.resposta;
            return retVal.Body.MudarStatusRevendaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusDistribuidorResponse Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap.MudarStatusDistribuidor(Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusDistribuidorRequest request) {
            return base.Channel.MudarStatusDistribuidor(request);
        }
        
        public bool MudarStatusDistribuidor(string usuario, string senha, string xml, out string resposta) {
            Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusDistribuidorRequest inValue = new Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusDistribuidorRequest();
            inValue.Body = new Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusDistribuidorRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.senha = senha;
            inValue.Body.xml = xml;
            Intelbras.CRM2013.Tests.SellOutWebService.MudarStatusDistribuidorResponse retVal = ((Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap)(this)).MudarStatusDistribuidor(inValue);
            resposta = retVal.Body.resposta;
            return retVal.Body.MudarStatusDistribuidorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Intelbras.CRM2013.Tests.SellOutWebService.PersistirRevendaResponse Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap.PersistirRevenda(Intelbras.CRM2013.Tests.SellOutWebService.PersistirRevendaRequest request) {
            return base.Channel.PersistirRevenda(request);
        }
        
        public bool PersistirRevenda(string usuario, string senha, string xml, out string resposta) {
            Intelbras.CRM2013.Tests.SellOutWebService.PersistirRevendaRequest inValue = new Intelbras.CRM2013.Tests.SellOutWebService.PersistirRevendaRequest();
            inValue.Body = new Intelbras.CRM2013.Tests.SellOutWebService.PersistirRevendaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.senha = senha;
            inValue.Body.xml = xml;
            Intelbras.CRM2013.Tests.SellOutWebService.PersistirRevendaResponse retVal = ((Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap)(this)).PersistirRevenda(inValue);
            resposta = retVal.Body.resposta;
            return retVal.Body.PersistirRevendaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Intelbras.CRM2013.Tests.SellOutWebService.PersistirDistribuidorResponse Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap.PersistirDistribuidor(Intelbras.CRM2013.Tests.SellOutWebService.PersistirDistribuidorRequest request) {
            return base.Channel.PersistirDistribuidor(request);
        }
        
        public bool PersistirDistribuidor(string usuario, string senha, string xml, out string resposta) {
            Intelbras.CRM2013.Tests.SellOutWebService.PersistirDistribuidorRequest inValue = new Intelbras.CRM2013.Tests.SellOutWebService.PersistirDistribuidorRequest();
            inValue.Body = new Intelbras.CRM2013.Tests.SellOutWebService.PersistirDistribuidorRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.senha = senha;
            inValue.Body.xml = xml;
            Intelbras.CRM2013.Tests.SellOutWebService.PersistirDistribuidorResponse retVal = ((Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap)(this)).PersistirDistribuidor(inValue);
            resposta = retVal.Body.resposta;
            return retVal.Body.PersistirDistribuidorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Intelbras.CRM2013.Tests.SellOutWebService.InserirDeParaProdutoCanalResponse Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap.InserirDeParaProdutoCanal(Intelbras.CRM2013.Tests.SellOutWebService.InserirDeParaProdutoCanalRequest request) {
            return base.Channel.InserirDeParaProdutoCanal(request);
        }
        
        public bool InserirDeParaProdutoCanal(string usuario, string senha, string xml, out string resposta) {
            Intelbras.CRM2013.Tests.SellOutWebService.InserirDeParaProdutoCanalRequest inValue = new Intelbras.CRM2013.Tests.SellOutWebService.InserirDeParaProdutoCanalRequest();
            inValue.Body = new Intelbras.CRM2013.Tests.SellOutWebService.InserirDeParaProdutoCanalRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.senha = senha;
            inValue.Body.xml = xml;
            Intelbras.CRM2013.Tests.SellOutWebService.InserirDeParaProdutoCanalResponse retVal = ((Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap)(this)).InserirDeParaProdutoCanal(inValue);
            resposta = retVal.Body.resposta;
            return retVal.Body.InserirDeParaProdutoCanalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Intelbras.CRM2013.Tests.SellOutWebService.InserirSaldoEstoqueResponse Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap.InserirSaldoEstoque(Intelbras.CRM2013.Tests.SellOutWebService.InserirSaldoEstoqueRequest request) {
            return base.Channel.InserirSaldoEstoque(request);
        }
        
        public bool InserirSaldoEstoque(string usuario, string senha, string xml, out string resposta) {
            Intelbras.CRM2013.Tests.SellOutWebService.InserirSaldoEstoqueRequest inValue = new Intelbras.CRM2013.Tests.SellOutWebService.InserirSaldoEstoqueRequest();
            inValue.Body = new Intelbras.CRM2013.Tests.SellOutWebService.InserirSaldoEstoqueRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.senha = senha;
            inValue.Body.xml = xml;
            Intelbras.CRM2013.Tests.SellOutWebService.InserirSaldoEstoqueResponse retVal = ((Intelbras.CRM2013.Tests.SellOutWebService.SelloutWSSoap)(this)).InserirSaldoEstoque(inValue);
            resposta = retVal.Body.resposta;
            return retVal.Body.InserirSaldoEstoqueResult;
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
    }
}
