//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelbras.CRM2013.Application.WCF.Pollux {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="MessageReceiver", ConfigurationName="Pollux.IMessageReceiver")]
    public interface IMessageReceiver {
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageReceiver/IMessageReceiver/PostRequest", ReplyAction="MessageReceiver/IMessageReceiver/PostRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="MessageReceiver/IMessageReceiver/PostRequestExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void PostRequest(string header, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageReceiver/IMessageReceiver/PostMessage", ReplyAction="MessageReceiver/IMessageReceiver/PostMessageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="MessageReceiver/IMessageReceiver/PostMessageExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool PostMessage(out string response, string message, string version, string contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="MessageReceiver/IMessageReceiver/Ping", ReplyAction="MessageReceiver/IMessageReceiver/PingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="MessageReceiver/IMessageReceiver/PingExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool Ping();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageReceiverChannel : Intelbras.CRM2013.Application.WCF.Pollux.IMessageReceiver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageReceiverClient : System.ServiceModel.ClientBase<Intelbras.CRM2013.Application.WCF.Pollux.IMessageReceiver>, Intelbras.CRM2013.Application.WCF.Pollux.IMessageReceiver {
        
        public MessageReceiverClient() {
        }
        
        public MessageReceiverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageReceiverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageReceiverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageReceiverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PostRequest(string header, string message) {
            base.Channel.PostRequest(header, message);
        }
        
        public bool PostMessage(out string response, string message, string version, string contract) {
            return base.Channel.PostMessage(out response, message, version, contract);
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
    }
}
