//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intelbras.CRM2013.Tests.PortalB2BNotaFiscal {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PortalB2BNotaFiscal.NotaFiscalSoap")]
    public interface NotaFiscalSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListagemDeNotasFiscaisPorEmitente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListagemDeNotasFiscaisPorEmitente(string codigoEstabelecimento, int codigoRepresentante, int codigoEmitente, System.DateTime dtInicial, System.DateTime dtFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListagemDeNotasFiscaisPorEmitente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListagemDeNotasFiscaisPorEmitenteAsync(string codigoEstabelecimento, int codigoRepresentante, int codigoEmitente, System.DateTime dtInicial, System.DateTime dtFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalhesDaNotaFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DetalhesDaNotaFiscal(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalhesDaNotaFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DetalhesDaNotaFiscalAsync(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItensDaNotaFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ItensDaNotaFiscal(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItensDaNotaFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ItensDaNotaFiscalAsync(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FaturasDaNotaFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FaturasDaNotaFiscal(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FaturasDaNotaFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FaturasDaNotaFiscalAsync(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotaisDaNotaFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TotaisDaNotaFiscal(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotaisDaNotaFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TotaisDaNotaFiscalAsync(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransportadoraDaNotaFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TransportadoraDaNotaFiscal(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransportadoraDaNotaFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TransportadoraDaNotaFiscalAsync(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NotaFiscalSoapChannel : Intelbras.CRM2013.Tests.PortalB2BNotaFiscal.NotaFiscalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotaFiscalSoapClient : System.ServiceModel.ClientBase<Intelbras.CRM2013.Tests.PortalB2BNotaFiscal.NotaFiscalSoap>, Intelbras.CRM2013.Tests.PortalB2BNotaFiscal.NotaFiscalSoap {
        
        public NotaFiscalSoapClient() {
        }
        
        public NotaFiscalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotaFiscalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotaFiscalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotaFiscalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListagemDeNotasFiscaisPorEmitente(string codigoEstabelecimento, int codigoRepresentante, int codigoEmitente, System.DateTime dtInicial, System.DateTime dtFinal) {
            return base.Channel.ListagemDeNotasFiscaisPorEmitente(codigoEstabelecimento, codigoRepresentante, codigoEmitente, dtInicial, dtFinal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListagemDeNotasFiscaisPorEmitenteAsync(string codigoEstabelecimento, int codigoRepresentante, int codigoEmitente, System.DateTime dtInicial, System.DateTime dtFinal) {
            return base.Channel.ListagemDeNotasFiscaisPorEmitenteAsync(codigoEstabelecimento, codigoRepresentante, codigoEmitente, dtInicial, dtFinal);
        }
        
        public System.Data.DataSet DetalhesDaNotaFiscal(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal) {
            return base.Channel.DetalhesDaNotaFiscal(codigoEstabelecimento, serieNotaFiscal, nrNotaFiscal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DetalhesDaNotaFiscalAsync(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal) {
            return base.Channel.DetalhesDaNotaFiscalAsync(codigoEstabelecimento, serieNotaFiscal, nrNotaFiscal);
        }
        
        public System.Data.DataSet ItensDaNotaFiscal(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal) {
            return base.Channel.ItensDaNotaFiscal(codigoEstabelecimento, serieNotaFiscal, nrNotaFiscal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ItensDaNotaFiscalAsync(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal) {
            return base.Channel.ItensDaNotaFiscalAsync(codigoEstabelecimento, serieNotaFiscal, nrNotaFiscal);
        }
        
        public System.Data.DataSet FaturasDaNotaFiscal(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal) {
            return base.Channel.FaturasDaNotaFiscal(codigoEstabelecimento, serieNotaFiscal, nrNotaFiscal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FaturasDaNotaFiscalAsync(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal) {
            return base.Channel.FaturasDaNotaFiscalAsync(codigoEstabelecimento, serieNotaFiscal, nrNotaFiscal);
        }
        
        public System.Data.DataSet TotaisDaNotaFiscal(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal) {
            return base.Channel.TotaisDaNotaFiscal(codigoEstabelecimento, serieNotaFiscal, nrNotaFiscal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TotaisDaNotaFiscalAsync(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal) {
            return base.Channel.TotaisDaNotaFiscalAsync(codigoEstabelecimento, serieNotaFiscal, nrNotaFiscal);
        }
        
        public System.Data.DataSet TransportadoraDaNotaFiscal(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal) {
            return base.Channel.TransportadoraDaNotaFiscal(codigoEstabelecimento, serieNotaFiscal, nrNotaFiscal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TransportadoraDaNotaFiscalAsync(string codigoEstabelecimento, string serieNotaFiscal, string nrNotaFiscal) {
            return base.Channel.TransportadoraDaNotaFiscalAsync(codigoEstabelecimento, serieNotaFiscal, nrNotaFiscal);
        }
    }
}
